---
# Time synchronization configuration tasks

# Set timezone to Asia/Shanghai
- name: Set timezone to Asia/Shanghai
  shell: timedatectl set-timezone Asia/Shanghai
  args:
    warn: false

      #- name: Attempt to update apt cache
      #  apt:
      #    update_cache: yes
      #  register: apt_update_result
      #  ignore_errors: yes

# Install chrony (different for Ubuntu and CentOS)
- name: Install chrony on (Debian/Ubuntu)
  apt:
    name: chrony
    state: present
  when: ansible_os_family == 'Debian'

- name: Install chrony on (RedHat/CentOS)
  yum:
    name: chrony
    state: present
  when: ansible_os_family == 'RedHat'

# Configure chrony.conf on master node
- name: Configure chrony.conf on master node (Debian/Ubuntu)
  template:
    src: chrony_master.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  when: "'master' in slurm_roles and ansible_os_family == 'Debian'"
  notify: restart chrony

- name: Configure chrony.conf on master node (RedHat/CentOS)
  template:
    src: chrony_master.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  when: "'master' in slurm_roles and ansible_os_family == 'RedHat'"
  notify: restart chrony

# Configure chrony.conf on other nodes
- name: Configure chrony.conf on other nodes (Debian/Ubuntu)
  template:
    src: chrony_node.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  when: "'master' not in slurm_roles and ansible_os_family == 'Debian'"
  notify: restart chrony

- name: Configure chrony.conf on other nodes (RedHat/CentOS)
  template:
    src: chrony_node.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  when: "'master' not in slurm_roles and ansible_os_family == 'RedHat'"
  notify: restart chrony

# Start and enable chrony service
- name: Start and enable chrony service
  systemd:
    name: chronyd
    state: started
    enabled: yes
  when: slurm_start_services | default(true)
